
disabled_rules:
  - trailing_whitespace
  
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_set_access_control
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  # - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_optional_binding
  - vertical_parameter_alignment_on_call
  - yoda_condition

excluded:
  - Carthage
  - CHTPZ/CoreLayer/GraphQL
  - CHTPZ/SourceryGenerated/
  - Pods
  - templates
  
cyclomatic_complexity:
  ignores_case_statements: true

explicit_type_interface:
  excluded:
    - local

identifier_name:
  min_length: 1
  max_length: 40
  allowed_symbols: _

modifier_order:
  preferred_modifier_order: [acl, override]

multiline_arguments:
  only_enforce_after_first_closure_on_first_line: true

nesting:
  type_level: 2

object_literal:
  color_literal: false

private_outlet:
  allow_private_set: true

type_body_length:
  warning: 300

type_name:
  min_length: 2
  max_length: 60

custom_rules:
  no_ui_alert_controller:
    included: ".*\\.swift"
    name: "UIAlertController usage"
    regex: "UIAlertController"
    match_kinds:
      - identifier

  no_print:
    included: ".*\\.swift"
    name: "stdlib print usage"
    regex: "print"
    match_kinds:
      - identifier

